version: "3.8"
services:
  server:
    build: ./ship_management
    container_name: server_c
    ports:
      - '4000:80'
  client:
    build: ./client_app
    container_name: client_c
    ports:
      - '3000:3000'